version: "3.9"
services:
  database-multiplication:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для веб-интерфейса управления
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: don
      RABBITMQ_DEFAULT_PASS: don

volumes:
  rabbitmq_data: