spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    consul:
      host: 192.168.0.109
  application:
    name: multiplication

server:
  error:
    include-message: always
    include-binding-errors: always

amqp:
  exchange:
    attempts: attempts.topic

endpoint:
  gamification-service:
    url: ${GAMIFICATION_SERVICE_URL:http://gamification/attempts}

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG